[package]
name = "update-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
serde = "1.0.197"
serde_json = "1.0.115"
tempfile = "3.10.1"
