[package]
name = "update-file"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "unicode"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tempfile = "3.10.1"
syn = "2.0"
quote = "1.0.36"

[lib]
proc-macro = true
